name: nextflow build
on:   
  workflow_dispatch: 
    inputs:
      BARCODE:
        description: 'Please input directory'
        required: true
        default: 'barcode01'
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: RUN NF
          run: |
            ls -lat
            echo HEY LOOK AT ME!!
            echo ${{ inputs.BARCODE}}
            echo we done here.
#            nextflow run epi2me-labs/wf-clone-validation --primers 'primers.tsv' --fastq 'input/${{ inputs.BARCODE}}' --out_dir "output/output-$(date '+%m%d-%H%M')"
          working-directory: /opt/nextflow

        - name: RUN LS
          run:
            ls -lat
#      - uses: actions/checkout@v3
#      - uses: nf-core/setup-nextflow@v1
