name: nextflow build
on:   
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - run: |
         nextflow run epi2me-labs/wf-clone-validation --help
         tree
        
#      - run:   nextflow run epi2me-labs/wf-clone-validation --fastq 'wf-clone-validation-demo/test_data/test/barcode01/test1.fastq' --primers 'wf-clone-validation-demo/data/primers.tsv'
